apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ./base/secret.yaml
  - ./base/configmap.yaml
  - ./base/deployment.yaml
  - ./base/service.yaml
  - ./base/ingress.yaml
  - ./base/plugin-configmap.yaml
  - ./base/init-hooks-configmap.yaml
