apiVersion: apps/v1
kind: Deployment
metadata:
  name: gau-cloud-http-deployment
  namespace: bao-${DEPLOY_ENV}-env
spec:
  replicas: 1
  selector:
    matchLabels:
      app: gau-cloud-http-service
  template:
    metadata:
      labels:
        app: gau-cloud-http-service
    spec:
      containers:
        - name: gau-cloud-http-service
          image: iamqbao/gau_cloud_service:latest
          imagePullPolicy: Always
          envFrom:
            - configMapRef:
                name: gau-cloud-${DEPLOY_ENV}-config
            - secretRef:
                name: gau-cloud-${DEPLOY_ENV}-secret
          resources:
            requests:
              cpu: "50m"
              memory: "128Mi"
            limits:
              cpu: "100m"
              memory: "256Mi"

---
#apiVersion: apps/v1
#kind: Deployment
#metadata:
#  name: gau-cloud-consumer-deployment
#  namespace: bao-${DEPLOY_ENV}-env
#spec:
#  replicas: 1
#  selector:
#    matchLabels:
#      app: gau-cloud-consumer-service
#  template:
#    metadata:
#      labels:
#        app: gau-cloud-consumer-service
#    spec:
#      containers:
#        - name: gau-cloud-consumer-service
#          image: iamqbao/gau_cloud_service:latest
#          imagePullPolicy: Always
#          envFrom:
#            - configMapRef:
#                name: gau-cloud-${DEPLOY_ENV}-config
#            - secretRef:
#                name: gau-cloud-${DEPLOY_ENV}-secret
#          args: ["consumer"]
#          resources:
#            requests:
#              cpu: "20m"
#              memory: "64Mi"
#            limits:
#              cpu: "50m"
#              memory: "128Mi"
#---
#apiVersion: apps/v1
#kind: Deployment
#metadata:
#  name: redis-cloud-deployment
#  namespace: bao-${DEPLOY_ENV}-env
#spec:
#  replicas: 1
#  selector:
#    matchLabels:
#      app: redis-cloud-service
#  template:
#    metadata:
#      labels:
#        app: redis-cloud-service
#    spec:
#      containers:
#        - name: redis-cloud-service
#          envFrom:
#            - configMapRef:
#                name: gau-cloud-${DEPLOY_ENV}-config
#            - secretRef:
#                name: gau-cloud-${DEPLOY_ENV}-secret
#          image: redis:7.2-alpine
#          resources:
#            requests:
#              cpu: "0.2"
#              memory: "128Mi"
#            limits:
#              cpu: "0.5"
#              memory: "256Mi"
