apiVersion: v1
kind: Secret
metadata:
  name: gau-cloud-${DEPLOY_ENV}-secret
  namespace: bao-${DEPLOY_ENV}-env
type: Opaque
stringData:
  PGPOOL_PASSWORD: "${PGPOOL_PASSWORD}"
  REDIS_PASSWORD: "${REDIS_PASSWORD}"
  RABBITMQ_PASSWORD: "${RABBITMQ_PASSWORD}"
  JWT_SECRET_KEY: "${JWT_SECRET_KEY}"
  PRIVATE_KEY: "${PRIVATE_KEY}"
  MINIO_ROOT_PASSWORD: "${MINIO_ROOT_PASSWORD}"