apiVersion: v1
kind: Service
metadata:
  name: gau-cloud-http-service
  namespace: bao-${DEPLOY_ENV}-env
spec:
  selector:
    app: gau-cloud-http-service
  ports:
    - name: http
      port: 8080
      targetPort: 8080
  type: ClusterIP
#---
#apiVersion: v1
#kind: Service
#metadata:
#  name: gau-cloud-consumer-service
#  namespace: bao-${DEPLOY_ENV}-env
#spec:
#  selector:
#    app: gau-cloud-consumer-service
#  ports:
#    - name: http
#      port: 8080
#      targetPort: 8080
#  type: ClusterIP
#---
#apiVersion: v1
#kind: Service
#metadata:
#  name: redis-cloud-service
#  namespace: bao-${DEPLOY_ENV}-env
#spec:
#  selector:
#    app: redis-cloud-service
#  ports:
#    - name: redis
#      port: 6379
#      targetPort: 6379
#  type: ClusterIP