apiVersion: v1
kind: ConfigMap
metadata:
  name: gau-temp-minio-${DEPLOY_ENV}-config
  namespace: bao-${DEPLOY_ENV}-env
  labels:
    app: bao-platform
    env: ${DEPLOY_ENV}
data:
  MINIO_BROWSER: "on"
#  MINIO_DOMAIN: "${WEB_HOSTING_BASE_DOMAIN}"