apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: gau-temp-minio-pvc
  namespace: bao-${DEPLOY_ENV}-env
  labels:
    app: bao-platform
    env: ${DEPLOY_ENV}
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: temp-minio-local
  resources:
    requests:
      storage: 50Gi