apiVersion: v1
kind: Secret
metadata:
  name: gau-temp-minio-${DEPLOY_ENV}-secret
  namespace: bao-${DEPLOY_ENV}-env
  labels:
    app: bao-platform
    env: ${DEPLOY_ENV}
type: Opaque
stringData:
  MINIO_ROOT_USER: "${MINIO_ROOT_USER}"
  MINIO_ROOT_PASSWORD: "${MINIO_ROOT_PASSWORD}"

