apiVersion: v1
kind: ConfigMap
metadata:
  name: gau-garage-${DEPLOY_ENV}-config
  namespace: bao-${DEPLOY_ENV}-env
data:
  garage.toml: |
    metadata_dir = "/meta"
    data_dir = "/data"
    db_engine = "lmdb"

    replication_mode = "none"
    compression_level = 1

    rpc_bind_addr = "[::]:3901"
    rpc_public_addr = "gau-garage-service:3901"

    [s3_api]
    s3_region = "garage"
    api_bind_addr = "[::]:3900"
    root_domain = ".${S3_API_DOMAIN}"

    [s3_web]
    bind_addr = "[::]:3902"
    root_domain = ".${S3_WEB_DOMAIN}"

    [admin]
    api_bind_addr = "0.0.0.0:3903"
