apiVersion: v1
kind: PersistentVolume
metadata:
  name: gau-garage-pv
  labels:
    app: bao-platform
    env: ${DEPLOY_ENV}
spec:
  capacity:
    storage: 180Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: garage-local
  local:
    path: /mnt/object-storage
  nodeAffinity:
    required:
      nodeSelectorTerms:
        - matchExpressions:
            - key: kubernetes.io/hostname
              operator: In
              values:
                - agent-7

