apiVersion: v1
kind: Secret
metadata:
  name: gau-garage-${DEPLOY_ENV}-secret
  namespace: bao-${DEPLOY_ENV}-env
  labels:
    app: bao-platform
    env: ${DEPLOY_ENV}
type: Opaque
stringData:
  GARAGE_RPC_SECRET: "${GARAGE_RPC_SECRET}"

