apiVersion: v1
kind: ConfigMap
metadata:
  name: gau-cloud-${DEPLOY_ENV}-config
  namespace: bao-${DEPLOY_ENV}-env
  labels:
    app: bao-platform
    env: ${DEPLOY_ENV}
data:
  PGPOOL_HOST: "${PGPOOL_HOST}"
  PGPOOL_DB: "${PGPOOL_DB}"
  PGPOOL_USER: "${PGPOOL_USER}"
  PGPOOL_PORT: "${PGPOOL_PORT}"
  PGPOOL_URL: "${PGPOOL_URL}"
  REDIS_HOST: "${REDIS_HOST}"
  REDIS_PORT: "${REDIS_PORT}"
  REDIS_DB: "${REDIS_DB}"
  RABBITMQ_HOST: "${RABBITMQ_HOST}"
  RABBITMQ_PORT: "${RABBITMQ_PORT}"
  RABBITMQ_USER: "${RABBITMQ_USER}"
  JWT_ALGORITHM: "${JWT_ALGORITHM}"
  JWT_EXPIRE: "${JWT_EXPIRE}"
  ALLOWED_DOMAINS: "${ALLOWED_DOMAINS}"
  GLOBAL_DOMAIN: "${GLOBAL_DOMAIN}"
  AUTHORIZATION_SERVICE_URL: "${AUTHORIZATION_SERVICE_URL}"
  UPLOAD_SERVICE_URL: "${UPLOAD_SERVICE_URL}"
  CDN_SERVICE_URL: "${CDN_SERVICE_URL}"
  GRAFANA_OTLP_ENDPOINT: "${GRAFANA_OTLP_ENDPOINT}"
  SERVICE_NAME: "${SERVICE_NAME}"
  DEPLOY_ENV: "${DEPLOY_ENV}"
  GROUP_NAME: "${GROUP_NAME}"
  MINIO_ENDPOINT: "${MINIO_ENDPOINT}"
  MINIO_ROOT_USER: "${MINIO_ROOT_USER}"
