apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: gau-minio-ingress
  namespace: bao-staging-env
  labels:
    app: bao-platform
    env: staging
  annotations:
    traefik.ingress.kubernetes.io/router.entrypoints: web
    traefik.ingress.kubernetes.io/router.middlewares: bao-staging-env-minio-upload-limit-2gb@kubernetescrd
spec:
  rules:
    - host: "s3.gauas.online"
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: gau-minio-service
                port:
                  number: 9000
    - host: "minio.gauas.online"
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: gau-minio-service
                port:
                  number: 9001