apiVersion: v1
kind: Secret
metadata:
  name: gau-minio-staging-secret
  namespace: bao-staging-env
  labels:
    app: bao-platform
    env: staging
type: Opaque
stringData:
  MINIO_ROOT_USER: "tnqbao"
  MINIO_ROOT_PASSWORD: "Qu_bao1604@tK"

