apiVersion: v1
kind: Secret
metadata:
  name: gau-localstack-${DEPLOY_ENV}-secret
  namespace: bao-${DEPLOY_ENV}-env
  labels:
    app: bao-platform
    env: ${DEPLOY_ENV}
type: Opaque
stringData:
  AWS_ACCESS_KEY_ID: "${AWS_ACCESS_KEY_ID}"
  AWS_SECRET_ACCESS_KEY: "{AWS_SECRET_ACCESS_KEY}"
