apiVersion: v1
kind: ConfigMap
metadata:
  name: gau-garage-staging-config
  namespace: bao-staging-env
data:
  garage.toml: |
    metadata_dir = "/meta"
    data_dir = "/data"
    db_engine = "lmdb"

    replication_mode = "none"
    compression_level = 1

    rpc_bind_addr = "[::]:3901"
    rpc_public_addr = "gau-garage-service:3901"

    [s3_api]
    s3_region = "garage"
    api_bind_addr = "[::]:3900"
    root_domain = ".s3.gauas.online"

    [s3_web]
    bind_addr = "[::]:3902"
    root_domain = ".web.gauas.online"

    [admin]
    api_bind_addr = "0.0.0.0:3903"
    admin_token = "Qu_bao1604_tK"
