apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: gau-garage-pvc
  namespace: bao-staging-env
  labels:
    app: bao-platform
    env: staging
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: garage-local
  resources:
    requests:
      storage: 180Gi

