apiVersion: v1
kind: Secret
metadata:
  name: gau-garage-staging-secret
  namespace: bao-staging-env
  labels:
    app: bao-platform
    env: staging
type: Opaque
stringData:
  GARAGE_RPC_SECRET: "9f4c2a7d1e8b6f0a3c5d7e9b1a4f6c2d8e0a9b7c5d3f1e4a6b8c0d2e9f4a1b2c"
  GARAGE_ADMIN_TOKEN: "Qu_bao1604_tK"
  GARAGE_ROOT_USER: "GKtnqbaoadmingauas"
  GARAGE_ROOT_PASSWORD: "Qu_bao1604@@tKQu_bao1604@tK"
