name: deploy_bucket_storage.yml

on:
  push:
    branches:
      - deploy/bucket-storage

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install Tailscale
        run: |
          curl -fsSL https://tailscale.com/install.sh | sh

      - name: Start Tailscale and authenticate
        run: |
          sudo tailscaled &
          sleep 3
          sudo tailscale up --authkey ${{ secrets.TAILSCALE_AUTH_KEY }}
          sleep 5

      - name: Install sshpass
        run: sudo apt-get update && sudo apt-get install -y sshpass


      - name: Download .env from server
        run: |
          sshpass -p "${{ secrets.SERVER_PASSWORD }}" scp -o StrictHostKeyChecking=no ${{ secrets.SERVER_USER }}@${{ secrets.SERVER_HOST }}:/home/tnqbao/.enviroment/gau-cloud-orchestrator/garage.env ./service/garage/k8s/.env

      - name: Download kubeconfig.yaml from server
        run: |
          mkdir -p ./service/garage/k8s
          sshpass -p "${{ secrets.SERVER_PASSWORD }}" scp -o StrictHostKeyChecking=no ${{ secrets.SERVER_USER }}@${{ secrets.SERVER_HOST }}:~/.secret/k8s/kubeconfig.yaml ./service/garage/k8s/kubeconfig.yaml

      - name: Set KUBECONFIG environment variable
        run: echo "KUBECONFIG=$GITHUB_WORKSPACE/service/garage/k8s/kubeconfig.yaml" >> $GITHUB_ENV

      - name: Check Kubernetes access
        run: kubectl get nodes

      - name: Make scripts executable
        run: |
          chmod +x ./service/garage/k8s/apply.sh
          chmod +x ./service/garage/k8s/apply_envsubst.sh

      - name: Apply manifests to Kubernetes
        working-directory: ./service/garage/k8s/
        run: ./apply.sh

      - name: Check active pods
        run: kubectl get pods -n bao-staging-env

      - name: Restart pods
        run: |
          kubectl rollout restart deployment gau-garage-deployment -n bao-staging-env
          sleep 10
          kubectl get pods -n bao-staging-env
