apiVersion: v1
kind: ConfigMap
metadata:
  name: gau-localstack-${DEPLOY_ENV}-config
  namespace: bao-${DEPLOY_ENV}-env
  labels:
    app: bao-platform
    env: ${DEPLOY_ENV}
data:
  DEPLOY_ENV: "${DEPLOY_ENV}"
  SERVICES: "${LOCALSTACK_SERVICES}"
  DEBUG: "0"
  PERSISTENCE: "1"
  SNAPSHOT_SAVE_STRATEGY: "ON_REQUEST"
  SNAPSHOT_LOAD_STRATEGY: "ON_STARTUP"
  AWS_DEFAULT_REGION: "${AWS_DEFAULT_REGION}"
  GATEWAY_LISTEN: "${GATEWAY_LISTEN}"
