apiVersion: apps/v1
kind: Deployment
metadata:
  name: gau-localstack-deployment
  namespace: bao-${DEPLOY_ENV}-env
  labels:
    app: bao-platform
    env: ${DEPLOY_ENV}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: gau-localstack-service
  template:
    metadata:
      labels:
        app: gau-localstack-service
    spec:
      containers:
        - name: localstack
          image: localstack/localstack:latest
          imagePullPolicy: IfNotPresent
          ports:
            - name: edge
              containerPort: 4566
              protocol: TCP
            - name: ext-services
              containerPort: 4571
              protocol: TCP
          env:
            - name: LOCALSTACK_PLUGIN_PATH
              value: /opt/localstack/plugins
            - name: LAMBDA_RUNTIME_ENVIRONMENT_TIMEOUT
              value: "900"
          envFrom:
            - configMapRef:
                name: gau-localstack-${DEPLOY_ENV}-config
            - secretRef:
                name: gau-localstack-${DEPLOY_ENV}-secret
          volumeMounts:
            - name: localstack-data
              mountPath: /var/lib/localstack
              subPath: data
#            - name: localstack-plugins
#              mountPath: /opt/localstack/plugins
          resources:
            requests:
              cpu: "100m"
              memory: "512Mi"
            limits:
              cpu: "500m"
              memory: "1Gi"
      volumes:
        - name: localstack-data
          persistentVolumeClaim:
            claimName: gau-localstack-pvc
#        - name: localstack-plugins
#          configMap:
#            name: localstack-plugins-cm