apiVersion: apps/v1
kind: Deployment
metadata:
  name: gau-localstack-deployment
  namespace: bao-${DEPLOY_ENV}-env
  labels:
    app: bao-platform
    env: ${DEPLOY_ENV}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: gau-localstack-service
  template:
    metadata:
      labels:
        app: gau-localstack-service
    spec:
      containers:
        - name: localstack
          image: localstack/localstack:latest
          imagePullPolicy: IfNotPresent
          ports:
            - name: edge
              containerPort: 4566
              protocol: TCP
            - name: ext-services
              containerPort: 4571
              protocol: TCP
          env:
            - name: LOCALSTACK_PLUGIN_PATH
              value: /opt/localstack/plugins
            - name: LAMBDA_RUNTIME_ENVIRONMENT_TIMEOUT
              value: "900"
          envFrom:
            - configMapRef:
                name: gau-localstack-${DEPLOY_ENV}-config
            - secretRef:
                name: gau-localstack-${DEPLOY_ENV}-secret
          volumeMounts:
            - name: localstack-data
              mountPath: /var/lib/localstack
            - name: init-hooks
              mountPath: /etc/localstack/init/ready.d
              subPath: ready.d
            - name: init-hooks
              mountPath: /etc/localstack/init/shutdown.d
              subPath: shutdown.d
#            - name: localstack-plugins
#              mountPath: /opt/localstack/plugins
          resources:
            requests:
              cpu: "100m"
              memory: "512Mi"
            limits:
              cpu: "500m"
              memory: "1Gi"
      initContainers:
        - name: setup-hooks
          image: busybox:latest
          command: ['sh', '-c']
          args:
            - |
              mkdir -p /hooks/ready.d
              cp /tmp/hooks/ready.d_01_restore.sh /hooks/ready.d/01_restore.sh
              cp /tmp/hooks/ready.d_02_start_backup_cron.sh /hooks/ready.d/02_start_backup_cron.sh
              chmod +x /hooks/ready.d/01_restore.sh
              chmod +x /hooks/ready.d/02_start_backup_cron.sh
          volumeMounts:
            - name: init-hooks-source
              mountPath: /tmp/hooks
            - name: init-hooks
              mountPath: /hooks
      volumes:
        - name: localstack-data
          persistentVolumeClaim:
            claimName: gau-localstack-pvc
        - name: init-hooks-source
          configMap:
            name: gau-localstack-init-hooks
        - name: init-hooks
          emptyDir: {}
#        - name: localstack-plugins
#          configMap:
#            name: localstack-plugins-cm
